#! /bin/bash

echo Default style
echo Default colors
echo Default width
echo With percentage
echo No elapsed time
echo No estimated remaining time
echo No label
echo No remove

for i in {0..10}
do
  ../src/vramsteg --percentage --min=0 --max=10 --current=$i
  sleep 1
done
echo

