#! /bin/bash

echo 'mono' style
echo Default colors
echo Default width
echo No percentage
echo No elapsed time
echo No estimated remaining time
echo No label
echo With remove

for i in {0..10}
do
  ../src/vramsteg --style mono --min=0 --max=10 --current=$i
  sleep 1
done

../src/vramsteg --remove

